/* WARNING: 本项目专属“粘人精”，严禁出现 Kiro、Krio、周棋洛等任何相关英文或拼音命名！ */
<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import type { ForumPost, ForumPostInteractionConfig } from '../../../types/forum'
const props=defineProps<{visible:boolean;post:ForumPost;busy?:boolean;error?:string}>()
const emit=defineEmits<{(e:'close'):void;(e:'confirm',config:ForumPostInteractionConfig):void}>()
const defaults=():ForumPostInteractionConfig=>({comments:true,replies:true,postLikes:true,commentLikes:true,shares:true,bookmarks:true,follows:false,views:true,countMode:'natural',commentCount:4,replyCount:2,actorCount:5,postLikeCount:4,commentLikeCount:3,shareCount:2,bookmarkCount:2,followCount:1,viewCount:20})
const form=reactive<ForumPostInteractionConfig>(defaults())
watch(()=>props.visible,value=>{if(value)Object.assign(form,defaults())})
const actions:Array<{key:keyof ForumPostInteractionConfig;label:string}>=[{key:'comments',label:'新增评论'},{key:'replies',label:'楼中楼回复'},{key:'postLikes',label:'NPC 点赞帖子'},{key:'commentLikes',label:'NPC 点赞评论'},{key:'shares',label:'NPC 转发/分享'},{key:'bookmarks',label:'NPC 收藏'},{key:'follows',label:'NPC 关注作者'},{key:'views',label:'浏览/热度变化'}]
const anySelected=computed(()=>actions.some(item=>Boolean(form[item.key])))
</script>
<template><div v-if="visible" class="overlay" @click.self="emit('close')"><section><header><div><b>当前帖子增量互动</b><small>只影响“{{post.content.slice(0,28)}}{{post.content.length>28?'…':''}}”</small></div><button @click="emit('close')">×</button></header><p class="notice">所有行为只由 NPC/角色账号执行，绝不会代替你的账号。</p><div class="mode"><button :class="{active:form.countMode==='natural'}" @click="form.countMode='natural'">自然决定数量</button><button :class="{active:form.countMode==='custom'}" @click="form.countMode='custom'">自定义数量</button></div><div class="actions"><label v-for="item in actions" :key="item.key"><input v-model="form[item.key]" type="checkbox"><span>{{item.label}}</span></label></div><div v-if="form.countMode==='custom'" class="numbers"><label v-for="item in [{k:'commentCount',t:'评论'},{k:'replyCount',t:'楼中楼'},{k:'postLikeCount',t:'帖子点赞'},{k:'commentLikeCount',t:'评论点赞'},{k:'shareCount',t:'分享'},{k:'bookmarkCount',t:'收藏'},{k:'followCount',t:'关注'},{k:'viewCount',t:'浏览'},{k:'actorCount',t:'参与 NPC'}]" :key="item.k"><span>{{item.t}}</span><input v-model.number="(form as any)[item.k]" type="number" :min="item.k==='actorCount'?1:0"></label></div><p v-if="error" class="error">{{error}}</p><footer><button @click="emit('close')">取消</button><button class="primary" :disabled="busy||!anySelected" @click="emit('confirm',{...form})">{{busy?'生成中…':'生成当前帖互动'}}</button></footer></section></div></template>
<style scoped>.overlay{position:fixed;inset:0;z-index:21000;display:flex;align-items:flex-end;background:rgba(0,0,0,.38)}section{box-sizing:border-box;width:100%;max-height:82vh;overflow:auto;border-radius:18px 18px 0 0;background:var(--sys-bg-secondary,#fff);padding:7px 15px calc(12px + env(safe-area-inset-bottom,0px))}header{display:flex;min-height:48px;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border-color,rgba(0,0,0,.06))}header div{display:flex;min-width:0;flex-direction:column;gap:2px}header b{font-size:14px}header small{max-width:260px;overflow:hidden;color:var(--text-tertiary,#999);font-size:10px;white-space:nowrap;text-overflow:ellipsis}header>button{border:0;background:transparent;color:var(--text-secondary,#777);font-size:20px}.notice{margin:10px 0;padding:8px;border-radius:9px;background:color-mix(in srgb,var(--accent-color,#576b95) 8%,transparent);color:var(--text-secondary,#666);font-size:10.5px}.mode{display:grid;grid-template-columns:1fr 1fr;gap:6px}.mode button{height:34px;border:1px solid transparent;border-radius:9px;background:var(--sys-bg-primary,#f4f5f6);color:var(--text-secondary,#666)}.mode button.active{border-color:color-mix(in srgb,var(--accent-color,#576b95) 45%,transparent);color:var(--accent-color,#576b95)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:12px 0}.actions label{display:flex;align-items:center;gap:7px;border-radius:9px;background:var(--sys-bg-primary,#f5f5f6);padding:9px;font-size:11px}.actions input{accent-color:var(--accent-color,#576b95)}.numbers{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.numbers label{display:flex;flex-direction:column;gap:4px;color:var(--text-tertiary,#888);font-size:10px}.numbers input{box-sizing:border-box;width:100%;height:31px;border:1px solid var(--border-color,#ddd);border-radius:8px;background:var(--sys-bg-primary,#f6f6f7);padding:0 8px}.error{color:#c44;font-size:10px}footer{display:flex;gap:8px;margin-top:13px}footer button{height:37px;flex:1;border:0;border-radius:10px;background:var(--sys-bg-primary,#f1f2f4);color:var(--text-secondary,#666);font-weight:600}footer .primary{background:var(--accent-color,#576b95);color:#fff}button:disabled{opacity:.4}@media(max-width:350px){.actions{grid-template-columns:1fr}.numbers{grid-template-columns:1fr 1fr}}</style>
