/* WARNING: 本项目专属“粘人精”，严禁出现 Kiro、Krio、周棋洛等任何相关英文或拼音命名！ */
<script setup lang="ts">
import type { MusicPlaylist, MusicTrack } from '../../../types/music'
defineProps<{ visible: boolean; playlist: MusicPlaylist | null; tracks: MusicTrack[]; loading: boolean; error: string }>()
const emit = defineEmits<{ (e: 'close'): void; (e: 'playAll'): void; (e: 'play', track: MusicTrack, index: number): void }>()
</script>

<template>
  <div v-if="visible" class="detail-mask" @click="emit('close')"><section class="detail-sheet" @click.stop><header><div><strong>歌单详情</strong><small>{{ loading ? '正在读取完整歌单…' : `${tracks.length} 首歌曲` }}</small></div><button @click="emit('close')">×</button></header><div class="detail-hero"><span class="detail-cover" :style="playlist?.coverUrl ? { backgroundImage: `url(${playlist.coverUrl})` } : {}"><i v-if="!playlist?.coverUrl">单</i></span><div><strong>{{ playlist?.name || '歌单' }}</strong><small>{{ playlist?.ownerName || playlist?.sourceId }}</small><p v-if="playlist?.description">{{ playlist.description }}</p></div></div><div class="detail-toolbar"><span>{{ playlist?.playCount || 0 }} 次播放</span><button :disabled="loading || !tracks.length" @click="emit('playAll')">播放全部</button></div><div class="detail-list"><div v-if="error" class="detail-state">{{ error }}</div><div v-else-if="loading" class="detail-state">正在加载歌曲列表</div><button v-for="(track,index) in tracks" v-else :key="track.id" class="track-row" @click="emit('play', track, index)"><span class="track-index">{{ index + 1 }}</span><span class="track-info"><strong>{{ track.title }}</strong><small>{{ track.artist }} · {{ track.album }}</small></span><span class="track-action">▶</span></button></div></section></div>
</template>

<style scoped>
.detail-mask{position:absolute;inset:0;z-index:84;display:flex;align-items:flex-end;background:rgba(0,0,0,.42);backdrop-filter:blur(8px)}.detail-sheet{width:100%;height:88%;display:flex;flex-direction:column;border:1px solid var(--music-card-border);border-radius:20px 20px 0 0;background:var(--music-card-bg);box-shadow:0 -8px 30px rgba(0,0,0,.12)}header{display:flex;align-items:center;justify-content:space-between;padding:17px 18px 13px;border-bottom:1px solid var(--music-divider)}header strong{display:block;font-size:17px}header small{display:block;margin-top:4px;color:var(--music-text-sub);font-size:11px}header button{width:32px;height:32px;border:0;border-radius:50%;background:var(--music-pill-bg);color:var(--music-text);font-size:22px}.detail-hero{display:flex;gap:13px;padding:14px 16px}.detail-cover{width:82px;height:82px;flex:0 0 auto;display:grid;place-items:center;border:1px solid var(--music-card-border);border-radius:13px;background:var(--music-secondary-bg);background-size:cover;background-position:center}.detail-cover i{font-style:normal;font-size:13px;font-weight:800}.detail-hero>div{min-width:0;padding-top:3px}.detail-hero strong{display:-webkit-box;overflow:hidden;font-size:15px;line-height:1.35;-webkit-box-orient:vertical;-webkit-line-clamp:2}.detail-hero small{display:block;margin-top:5px;color:var(--music-text-sub);font-size:10px}.detail-hero p{display:-webkit-box;overflow:hidden;margin:7px 0 0;color:var(--music-text-sub);font-size:9px;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:2}.detail-toolbar{display:flex;align-items:center;justify-content:space-between;padding:0 16px 12px;color:var(--music-text-sub);font-size:10px}.detail-toolbar button{height:36px;padding:0 17px;border:0;border-radius:11px;background:var(--music-text);color:var(--music-bg);font-size:11px;font-weight:750}.detail-toolbar button:disabled{opacity:.45}.detail-list{min-height:0;overflow:auto;padding:0 16px calc(24px + env(safe-area-inset-bottom));display:flex;flex-direction:column}.track-row{width:100%;min-height:58px;display:flex;align-items:center;gap:10px;border:0;border-bottom:1px solid var(--music-divider);background:transparent;color:var(--music-text);text-align:left}.track-index{width:24px;color:var(--music-text-sub);font-size:10px;text-align:center}.track-info{min-width:0;flex:1}.track-info strong,.track-info small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.track-info strong{font-size:13px}.track-info small{margin-top:4px;color:var(--music-text-sub);font-size:9px}.track-action{color:var(--music-text-sub);font-size:10px}.detail-state{padding:28px 12px;border:1px solid var(--music-card-border);border-radius:14px;background:var(--music-secondary-bg);color:var(--music-text-sub);font-size:11px;text-align:center}
</style>
