/* WARNING: 本项目专属“粘人精”，严禁出现 Kiro、Krio、周棋洛等任何相关英文或拼音命名！ */
<script setup lang="ts">
import type { MusicPlaylist } from '../../../types/music'
defineProps<{ visible: boolean; title: string; subtitle: string; playlists: MusicPlaylist[] }>()
const emit = defineEmits<{ (e: 'close'): void; (e: 'select', playlist: MusicPlaylist): void }>()
</script>

<template>
  <div v-if="visible" class="collection-mask" @click="emit('close')"><section class="collection-sheet" @click.stop><header><div><strong>{{ title }}</strong><small>{{ subtitle }}</small></div><button @click="emit('close')">×</button></header><div class="collection-body"><div v-if="!playlists.length" class="collection-empty">当前来源暂时没有返回可查看的歌单</div><button v-for="playlist in playlists" :key="`${playlist.sourceId}:${playlist.id}`" class="collection-card" @click="emit('select', playlist)"><span class="collection-cover" :style="playlist.coverUrl ? { backgroundImage: `url(${playlist.coverUrl})` } : {}"><i v-if="!playlist.coverUrl">单</i></span><span class="collection-info"><strong>{{ playlist.name }}</strong><small>{{ playlist.ownerName || playlist.sourceId }} · {{ playlist.trackCount || '多' }} 首 · {{ playlist.playCount || 0 }} 次播放</small></span><b>›</b></button></div></section></div>
</template>

<style scoped>
.collection-mask{position:absolute;inset:0;z-index:83;display:flex;align-items:flex-end;background:rgba(0,0,0,.42);backdrop-filter:blur(8px)}.collection-sheet{width:100%;max-height:86%;display:flex;flex-direction:column;border:1px solid var(--music-card-border);border-radius:20px 20px 0 0;background:var(--music-card-bg);box-shadow:0 -8px 30px rgba(0,0,0,.12)}header{display:flex;align-items:center;justify-content:space-between;padding:19px 18px 14px;border-bottom:1px solid var(--music-divider)}header strong{display:block;font-size:17px}header small{display:block;margin-top:4px;color:var(--music-text-sub);font-size:11px}header button{width:32px;height:32px;border:0;border-radius:50%;background:var(--music-pill-bg);color:var(--music-text);font-size:22px}.collection-body{overflow:auto;padding:14px 16px calc(24px + env(safe-area-inset-bottom));display:flex;flex-direction:column;gap:10px}.collection-card{width:100%;min-height:64px;padding:8px;display:flex;align-items:center;gap:11px;border:1px solid var(--music-card-border);border-radius:14px;background:var(--music-secondary-bg);color:var(--music-text);text-align:left}.collection-cover{width:50px;height:50px;flex:0 0 auto;display:grid;place-items:center;border:1px solid var(--music-card-border);border-radius:10px;background:var(--music-card-bg);background-size:cover;background-position:center}.collection-cover i{font-size:11px;font-style:normal;font-weight:800}.collection-info{min-width:0;flex:1}.collection-info strong,.collection-info small{display:block}.collection-info strong{overflow:hidden;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.collection-info small{margin-top:5px;color:var(--music-text-sub);font-size:9px}.collection-card>b{color:var(--music-text-sub);font-size:21px;font-weight:400}.collection-empty{padding:28px 14px;border:1px solid var(--music-card-border);border-radius:14px;background:var(--music-secondary-bg);color:var(--music-text-sub);font-size:11px;text-align:center}
</style>
