import assert from 'node:assert/strict'
const memory = new Map<string, string>()
Object.defineProperty(globalThis, 'localStorage', { value: { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value), removeItem: (key: string) => memory.delete(key), key: (index: number) => [...memory.keys()][index] ?? null, clear: () => memory.clear(), get length() { return memory.size } } })
const { emptyForumSnapshot } = await import('../src/services/forumRepository')
const { createForumDistributionPlan, normalizeForumGenerationConfig } = await import('../src/services/forumGeneration')
const snapshot = emptyForumSnapshot(); const now=Date.now()
snapshot.settings.activeAccountId='viewer';snapshot.circles.push({id:'owned',name:'小说交流',avatar:'小',description:'聊小说',contentScope:'阅读、写作和具体作品讨论',rules:[],tags:['小说'],creatorAccountId:'viewer',administratorAccountIds:['viewer'],memberCount:18,activityScore:1,searchable:true,isPublic:true,joinMode:'public',contentPermissions:['text'],anonymousMode:'per-post',adminCanResolveAnonymous:false,allowPoll:true,allowLottery:false,mediaPermissions:[],participantSubjectIds:[],aiPopulation:0,aiActivity:'off',createdAt:now,source:'user'},{id:'random',name:'今天吃什么',avatar:'吃',description:'聊吃饭',contentScope:'具体餐食、店铺和做饭',rules:[],tags:['美食'],creatorAccountId:'viewer',administratorAccountIds:[],memberCount:800,activityScore:1,searchable:true,isPublic:true,joinMode:'public',contentPermissions:['text'],anonymousMode:'per-post',adminCanResolveAnonymous:false,allowPoll:true,allowLottery:false,mediaPermissions:[],participantSubjectIds:[],aiPopulation:0,aiActivity:'off',createdAt:now,source:'generated'})
const authors=Array.from({length:18},(_,index)=>`author-${index}`)
const config=normalizeForumGenerationConfig({rangeDays:3,postCount:20,commentMin:60,commentMax:60,publicPostCount:14,circlePostCount:6,strangerAuthorMin:18,strangerAuthorMax:18,requiredCharacterAccountIds:[],includeOwnedCircles:true,ownedCirclePostCounts:{owned:3},randomCircleCount:1,worldBookIds:[]})
const plan=createForumDistributionPlan(snapshot,'session','batch',config,authors,['random'])
assert.equal(plan.slots.length,20)
assert.equal(plan.slots.filter(item=>item.circleId).length,6)
assert.equal(plan.slots.filter(item=>item.circleId==='owned').length,3)
assert.equal(plan.slots.reduce((sum,item)=>sum+item.commentTarget,0),60)
assert.ok(plan.slots.some(item=>item.commentTarget===0),'应存在零评论帖子')
assert.ok(new Set(plan.slots.map(item=>item.authorAccountId)).size>=18,'20 篇帖子应优先使用至少 18 位作者')
assert.ok(plan.slots.every(item=>Number(item.createdAt)>=now-3*86400000-1000&&Number(item.createdAt)<=Date.now()+1000),'帖子时间应分布在配置范围内')
console.log('forum generation tests passed')
