<script setup lang="ts">
import type { ForumCircle, ForumMediaItem, ForumPost, ForumQuoteContent, ForumUser } from '../../../types/forum'
import ForumHeader from '../components/ForumHeader.vue'
import ForumFeedItem from '../components/ForumFeedItem.vue'
import ForumEmptyState from '../components/ForumEmptyState.vue'
const props=defineProps<{circle:ForumCircle;posts:ForumPost[];joined:boolean;busy:boolean;error:string}>()
const emit=defineEmits<{(e:'back'):void;(e:'join'):void;(e:'publish'):void;(e:'generate'):void;(e:'settings'):void;(e:'click-post',p:ForumPost):void;(e:'click-user',u:ForumUser):void;(e:'like',p:ForumPost):void;(e:'bookmark',p:ForumPost):void;(e:'preview-image',i:number,m:ForumMediaItem[]):void;(e:'click-quote',q:ForumQuoteContent):void}>()
</script>
<template>
  <div class="circle-view"><ForumHeader :title="circle.name" show-back @back="emit('back')"><template #right><button v-if="circle.administratorAccountIds.length" class="icon-more" @click="emit('settings')">•••</button></template></ForumHeader>
    <div class="circle-scroll"><section class="circle-hero"><div class="hero-main"><span>{{circle.avatar||circle.name[0]}}</span><div><h2>{{circle.name}}</h2><p>{{circle.memberCount}} 人 · {{circle.aiActivity==='off'?'居民活动已关闭':'会自然更新'}}</p></div><button v-if="!joined" @click="emit('join')">加入</button></div><p class="description">{{circle.description}}</p><p v-if="circle.announcement" class="announcement"><b>公告</b>{{circle.announcement}}</p><div class="circle-actions"><button :disabled="!joined" @click="emit('publish')">发布</button><button :disabled="busy||circle.aiActivity==='off'" @click="emit('generate')">{{busy?'更新中…':'看看新动态'}}</button></div><p v-if="error" class="error-line">{{error}}</p></section>
      <div class="section-label">圈内动态</div><ForumFeedItem v-for="post in posts" :key="post.id" :post="post" @click-post="emit('click-post',post)" @click-user="u=>emit('click-user',u)" @like="p=>emit('like',p)" @bookmark="p=>emit('bookmark',p)" @preview-image="(i,m)=>emit('preview-image',i,m)" @click-quote="q=>emit('click-quote',q)"/><ForumEmptyState v-if="!posts.length" title="圈子还很安静" description="你可以发布内容，或手动生成一批新内容"/>
    </div>
  </div>
</template>
<style scoped>
.circle-view{display:flex;flex-direction:column;height:100%;background:var(--sys-bg-primary,#f5f5f7)}.icon-more{border:0;background:transparent;color:var(--text-secondary,#777);padding:7px 3px;letter-spacing:2px}.circle-scroll{flex:1;overflow:auto}.circle-hero{padding:14px 16px;background:var(--sys-bg-secondary,#fff)}.hero-main{display:flex;align-items:center;min-width:0;gap:11px}.hero-main>span{display:flex;flex:0 0 46px;height:46px;align-items:center;justify-content:center;border-radius:13px;background:var(--sys-bg-tertiary,#eceef1);font-size:17px;font-weight:650}.hero-main>div{min-width:0;flex:1}.hero-main h2{margin:0 0 3px;font-size:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hero-main p{margin:0;color:var(--text-tertiary,#999);font-size:11px}.hero-main>button,.circle-actions button{height:29px;border:1px solid var(--accent-color,#2b7de9);border-radius:999px;background:transparent;color:var(--accent-color,#2b7de9);padding:0 12px;font-size:12px}.description{margin:12px 0 0;font-size:13px;line-height:1.5;color:var(--text-secondary,#666)}.announcement{margin:9px 0 0;padding:8px 10px;border-radius:9px;background:var(--sys-bg-primary,#f5f5f7);font-size:11.5px;color:var(--text-secondary,#666);line-height:1.45}.announcement b{margin-right:7px;color:var(--text-primary,#333)}.circle-actions{display:flex;gap:7px;margin-top:11px}.circle-actions button{border-color:var(--border-color,#ddd);color:var(--text-primary,#333)}.circle-actions button:disabled{opacity:.35}.error-line{margin:8px 0 0;font-size:11px;color:#d04a4a;line-height:1.4}.section-label{padding:9px 16px 6px;color:var(--text-tertiary,#999);font-size:11px;font-weight:600;background:var(--sys-bg-primary,#f5f5f7)}@media(max-width:340px){.circle-hero{padding-left:12px;padding-right:12px}.hero-main>span{flex-basis:42px;height:42px}.hero-main>button{padding:0 9px}}
</style>
