<script setup lang="ts">
import { computed, ref } from 'vue'
import type { ForumCircle, ForumMediaItem, ForumPostType, ForumUser } from '../../../types/forum'
import ForumHeader from '../components/ForumHeader.vue'
import ForumAvatar from '../components/ForumAvatar.vue'

const props = defineProps<{ currentUser: ForumUser; circles: ForumCircle[]; initialCircleId?: string; mediaBusy?: boolean; mediaError?: string }>()
const emit = defineEmits<{ (e:'back'):void; (e:'media',file:File,type:ForumMediaItem['type']):void; (e:'generate-image',prompt:string):void; (e:'generate-voice',text:string):void; (e:'build-video',value:{image:ForumMediaItem;voice?:ForumMediaItem;subtitle:string}):void; (e:'publish',value:{content:string;type:ForumPostType;circleId?:string;media:ForumMediaItem[];pollOptions?:string[];lottery?:{prize:string;winnerCount:number;drawAt:number;conditions:['none'];anonymous:false}}):void }>()
const content=ref('');const type=ref<ForumPostType>('text');const circleId=ref(props.initialCircleId||'');const media=ref<ForumMediaItem[]>([]);const pollOptions=ref(['','']);const prize=ref('');const winnerCount=ref(1);const fileInput=ref<HTMLInputElement|null>(null)
const allowedTypes=computed(()=>{const circle=props.circles.find(item=>item.id===circleId.value);return circle?.contentPermissions||['text','single-image','multi-image','poll','voice','short-video','anonymous','lottery']})
const canPublish=computed(()=>Boolean(content.value.trim()||media.value.length||type.value==='poll'&&pollOptions.value.filter(Boolean).length>1||type.value==='lottery'&&prize.value.trim()))
const selectType=(value:ForumPostType)=>{type.value=value;if(value==='single-image'||value==='multi-image')fileInput.value?.click()}
const upload=(event:Event)=>{const files=Array.from((event.target as HTMLInputElement).files||[]);files.forEach(file=>emit('media',file,file.type.startsWith('audio/')?'voice':'image'));(event.target as HTMLInputElement).value=''}
const addMedia=(item:ForumMediaItem)=>media.value.push(item)
defineExpose({addMedia})
const buildVideo=()=>{const image=media.value.find(item=>item.type==='image');if(image)emit('build-video',{image,voice:media.value.find(item=>item.type==='voice'),subtitle:content.value})}
const submit=()=>emit('publish',{content:content.value,type:type.value,circleId:circleId.value||undefined,media:media.value,pollOptions:type.value==='poll'?pollOptions.value:undefined,lottery:type.value==='lottery'?{prize:prize.value,winnerCount:winnerCount.value,drawAt:Date.now(),conditions:['none'],anonymous:false}:undefined})
</script>
<template>
  <div class="composer-view">
    <ForumHeader title="发布" show-back @back="emit('back')"><template #right><button class="publish-action" :disabled="!canPublish" @click="submit">发布</button></template></ForumHeader>
    <div class="composer-scroll">
      <div class="author-line"><ForumAvatar :src="currentUser.avatar" :name="currentUser.name" size="md"/><select v-model="circleId" class="circle-select"><option value="">公开发布</option><option v-for="circle in circles" :key="circle.id" :value="circle.id">{{circle.name}}</option></select></div>
      <textarea v-model="content" class="content-area" maxlength="5000" :placeholder="type==='anonymous'?'匿名说点什么…':'分享此刻的想法…'"></textarea>
      <div v-if="media.length" class="media-preview"><div v-for="(item,index) in media" :key="item.id"><img v-if="item.type==='image'" :src="item.url"/><span v-else>{{item.type==='voice'?'语音':'媒体'}}</span><button @click="media.splice(index,1)">×</button></div></div>
      <div v-if="type==='short-video'" class="extra-editor"><small>使用图片、TTS、字幕和动画实时播放，不编码视频文件。</small><button :disabled="!media.some(item=>item.type==='image')" @click="buildVideo">组合当前素材</button></div>
      <p v-if="mediaError" class="media-error">{{mediaError}}</p>
      <div v-if="type==='poll'" class="extra-editor"><label v-for="(_,index) in pollOptions" :key="index"><span>{{index+1}}</span><input v-model="pollOptions[index]" maxlength="80" placeholder="选项内容"/></label><button v-if="pollOptions.length<8" @click="pollOptions.push('')">＋ 添加选项</button></div>
      <div v-if="type==='lottery'" class="extra-editor"><label><span>奖品</span><input v-model="prize" maxlength="80" placeholder="奖品名称"/></label><label><span>名额</span><input v-model.number="winnerCount" type="number" min="1" max="100"/></label><small>开奖由本地随机规则执行，不交给 AI 决定。</small></div>
    </div>
    <div class="ai-tools"><button :disabled="mediaBusy||!content.trim()" @click="emit('generate-image',content)">AI 生图</button><button :disabled="mediaBusy||!content.trim()" @click="emit('generate-voice',content)">文字转语音</button><span v-if="mediaBusy">生成中…</span></div>
    <div class="composer-tools"><button v-for="item in [{id:'text',t:'文字'},{id:'multi-image',t:'图片'},{id:'voice',t:'语音'},{id:'short-video',t:'短视频'},{id:'poll',t:'投票'},{id:'lottery',t:'抽奖'},{id:'anonymous',t:'匿名'}]" :key="item.id" :disabled="!allowedTypes.includes(item.id as ForumPostType)" :class="{active:type===item.id}" @click="selectType(item.id as ForumPostType)">{{item.t}}</button></div>
    <input ref="fileInput" class="hidden-file" type="file" accept="image/*,audio/*" multiple @change="upload"/>
  </div>
</template>
<style scoped>
.composer-view{display:flex;flex-direction:column;height:100%;background:var(--sys-bg-secondary,#fff)}.publish-action{height:30px;border:0;border-radius:999px;padding:0 13px;background:var(--accent-color,#2b7de9);color:#fff;font-size:12.5px;font-weight:600}.publish-action:disabled{opacity:.35}.composer-scroll{flex:1;min-height:0;overflow:auto;padding:13px 16px}.author-line{display:flex;align-items:center;gap:10px}.circle-select{min-width:0;max-width:160px;height:30px;border:1px solid var(--border-color,#e5e5e5);border-radius:999px;background:var(--sys-bg-primary,#f7f7f8);color:var(--text-secondary,#666);padding:0 25px 0 10px;font:inherit;font-size:12px;outline:0}.content-area{box-sizing:border-box;width:100%;min-height:148px;border:0;resize:none;outline:0;background:transparent;padding:15px 1px;color:var(--text-primary,#222);font:inherit;font-size:15px;line-height:1.65}.media-preview{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.media-preview>div{position:relative;display:flex;aspect-ratio:1;align-items:center;justify-content:center;border-radius:10px;overflow:hidden;background:var(--sys-bg-tertiary,#eee);font-size:12px;color:var(--text-secondary,#777)}.media-preview img{width:100%;height:100%;object-fit:cover}.media-preview button{position:absolute;top:4px;right:4px;width:20px;height:20px;border:0;border-radius:50%;background:rgba(0,0,0,.55);color:#fff}.extra-editor{display:flex;flex-direction:column;gap:8px;padding:11px;border-radius:12px;background:var(--sys-bg-primary,#f6f6f8)}.extra-editor label{display:flex;align-items:center;gap:8px;min-width:0}.extra-editor label span{flex:0 0 34px;font-size:12px;color:var(--text-secondary,#777)}.extra-editor input{min-width:0;flex:1;height:32px;border:1px solid var(--border-color,#e2e2e2);border-radius:8px;background:var(--sys-bg-secondary,#fff);padding:0 9px;color:var(--text-primary,#222);font:inherit;font-size:13px;outline:0}.extra-editor>button{align-self:flex-start;border:0;background:transparent;color:var(--accent-color,#2b7de9);padding:3px;font-size:12px}.extra-editor small{color:var(--text-tertiary,#999);font-size:11px}.composer-tools{display:flex;gap:5px;overflow-x:auto;padding:8px 12px calc(8px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--border-color,rgba(0,0,0,.06));scrollbar-width:none}.composer-tools button{flex:0 0 auto;height:29px;border:0;border-radius:999px;background:var(--sys-bg-primary,#f2f3f5);color:var(--text-secondary,#666);padding:0 10px;font-size:11.5px}.composer-tools button.active{background:color-mix(in srgb,var(--accent-color,#2b7de9) 13%,transparent);color:var(--accent-color,#2b7de9);font-weight:600}.composer-tools button:disabled{opacity:.3}.hidden-file{display:none}@media(max-width:340px){.composer-scroll{padding-left:12px;padding-right:12px}.composer-tools{padding-left:8px;padding-right:8px}.circle-select{max-width:125px}}
.ai-tools{display:flex;align-items:center;gap:6px;padding:7px 12px 0;border-top:1px solid var(--border-color,rgba(0,0,0,.06))}.ai-tools button{height:27px;border:0;border-radius:999px;background:var(--sys-bg-primary,#f2f3f5);color:var(--text-secondary,#666);padding:0 9px;font-size:11px}.ai-tools button:disabled{opacity:.35}.ai-tools span{font-size:10.5px;color:var(--text-tertiary,#999)}.media-error{margin:8px 0;color:#d04a4a;font-size:11px;line-height:1.4}
</style>
